services:
  db:
    image: postgres:latest
    container_name: postgres_jeopardy
    environment:
      POSTGRES_USER: ${JEOPARDY_DB_USER:-jeopardy}
      POSTGRES_PASSWORD: ${JEOPARDY_DB_PASSWORD:-jeopardy}
      POSTGRES_DB: ${JEOPARDY_DB_NAME:-jeopardy}
    ports:
      - "${JEOPARDY_DB_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${JEOPARDY_DB_USER:-jeopardy}" ]
      interval: 30s
      timeout: 10s
      retries: 1
      start_period: 5s

  redis:
    image: redis:latest
    container_name: redis_jeopardy
    ports:
      - "${JEOPARDY_REDIS_PORT:-6379}:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 30s
      timeout: 10s
      retries: 1
      start_period: 5s

volumes:
  postgres_data:
