name: Jeopardy CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      JEOPARDY_DB_HOST: "localhost"
      JEOPARDY_DB_PORT: 5432
      JEOPARDY_DB_NAME: "jeopardy"
      JEOPARDY_DB_USER: "jeopardy"
      JEOPARDY_DB_PASSWORD: "jeopardy"

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_DB: ${{ env.JEOPARDY_DB_HOST }}
          POSTGRES_USER: ${{ env.JEOPARDY_DB_USER }}
          POSTGRES_PASSWORD: ${{ env.JEOPARDY_DB_PASSWORD }}
        options: >-
          --health-cmd "pg_isready -U ${{ env.JEOPARDY_DB_USER }}"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry config virtualenvs.create false
          poetry install --with dev

      - name: Run code formatter (black)
        run: |
          black --check src

      - name: Sort imports (isort)
        run: |
          isort --check src

      - name: Lint with flake8
        run: |
          flake8

      - name: Run tests with pytest
        run: |
          pytest
