name: Jeopardy CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      JEOPARDY_DB_USER: jeopardy
      JEOPARDY_DB_PASSWORD: jeopardy
      JEOPARDY_DB_NAME: jeopardy

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_DB: $JEOPARDY_DB_NAME
          POSTGRES_USER: $JEOPARDY_DB_USER
          POSTGRES_PASSWORD: $JEOPARDY_DB_PASSWORD
        options: >-
          --health-cmd "pg_isready -U $JEOPARDY_DB_USER"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry config virtualenvs.create false
          poetry install --with dev

      - name: Run code formatter (black)
        run: |
          black --check src

      - name: Sort imports (isort)
        run: |
          isort --check src

      - name: Lint with flake8
        run: |
          flake8

#      - name: Run tests with pytest
#        run: |
#          pytest
